#!/usr/bin/env python2

from __future__ import print_function
import sys, os, re, subprocess as sp
from setuptools import setup

########################################

# Based on this recipe, adapted for Python 3, Git 2.8.x, and PEP-440 version identifiers
#   http://blogs.nopcode.org/brainstorm/2013/05/20/pragmatic-python-versioning-via-setuptools-and-git-tags/
#   https://www.python.org/dev/peps/pep-0440/#version-scheme

# Fetch version from git tags, and write to version.py.
# Also, when git is not available (PyPi package), use stored version.py.
version_py = os.path.join(os.path.dirname(__file__), 'pysimg', 'version.py')

try:
    version_git = sp.check_output(["git", "describe", "--tags", "--dirty=_dirty"]).strip().decode('ascii')
    final, dev, blob, dirty = re.match(r'v?((?:\d+\.)*\d+)(?:-(\d+)-(g[a-z0-9]+))?(_dirty)?', version_git).groups()
    version_pep = final+('.dev%s+%s'%(dev,blob) if dev else '')+(dirty if dirty else '')
except:
    d = {}
    with open(version_py, 'r') as fh:
        exec(fh.read(), d)
        version_pep = d['__version__']
else:
    with open(version_py, 'w') as fh:
        print("# Do not edit this file, versioning is governed by git tags", file=fh)
        print('__version__="%s"' % version_pep, file=fh)

########################################

setup(name="pysimg",
      version=version_pep,
      description=("Pure-Python tools for handling Android fastboot's sparse image format"),
      long_description=open('README.md').read(),
      author="Daniel Lenski",
      author_email="dlenski@gmail.com",
      install_requires=[ 'enum34>=1.0' ],
      license='GPL v3 or later',
      url="https://github.com/dlenski/PySIMG",
      packages=["pysimg"],
      entry_points={ 'console_scripts': [ 'img2simg=pysimg.__main__:main' ] }
      )
